{% set name = "wagtail-resume" %}
{% set version = "2.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wagtail_resume-{{ version }}.tar.gz
  sha256: e5015a311a2c5d9d8d975871c09d7b0551937c386f7e07d63e72ff3c017e4485

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }}
    - django >=3.2.0
    - wagtail >=4.0.0
    - wagtail-markdown >=0.10.0
    - wagtail-metadata >=4.0.0
    - weasyprint >=59.0.0

test:
  imports:
    - wagtail_resume
  #commands:
    #- pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/adinhodovic/wagtail-resume
  summary: A Wagtail project made to simplify creation of resumes for developers.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
