{% set name = "wagtail-resume" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wagtail_resume-{{ version }}.tar.gz
  sha256: 8bfaeaf407562b6735691284b0260308639093ab86f79db229ae1c9cb93bcc27

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.8,<4.0.0
    - django >=3.2.0,<6.0.0
    - wagtail >=3.0.0,<7.0.0
    - wagtail-markdown >=0.10.0,<0.12.0
    - wagtail-metadata >=3.0.0,<6.0.0
    - weasyprint >=52.0.0,<53.0.0

test:
  imports:
    - wagtail_resume
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/adinhodovic/wagtail-resume
  summary: A Wagtail project made to simplify creation of resumes for developers.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
