# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: wagtail-resume
  version: "2.10.2"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/wagtail_resume-${{ version }}.tar.gz
  sha256: d29db439d5be4e63459a4410d91c9e1c0cc3b302b4aa30648eb030dc5dc813ea

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - django >=3.2.0,<6.0.0
    - wagtail >=4.0.0,<8.0.0
    - wagtail-markdown >=0.10.0,<0.14.0
    - wagtail-metadata >=4.0.0,<6.0.0
    - weasyprint >=59.0.0,<62.0.0

tests:
  - python:
      imports:
        - wagtail_resume
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: A Wagtail project made to simplify creation of resumes for developers.
  homepage: https://github.com/adinhodovic/wagtail-resume
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
